services:
  scrape-mediux:
    image: docker.io/zhyph/scrape-mediux
    container_name: scrape-mediux
    environment:
      - LOG_LEVEL=info # Set the log level (debug, info, warning, error)
      - TZ=Etc/UTC # Set your timezone
    volumes:
      - /path/to/config:/config # REQUIRED
      - /path/to/media:/data # REQUIRED, root_folder in config.json (or args) must match this
      - /path/to/kometa/metadata:/out # OPTIONAL, output_dir in config.json (or args) must match this